CREATE TABLE TEAM 
(
    TEAM_ID VARCHAR2(3),
    NAME VARCHAR2(12) NOT NULL,
    BUDGET FLOAT,
    CONSTRAINT B_CK CHECK (BUDGET>=0)
);

CREATE TABLE DRIVER 
(
    DRIVER_NO VARCHAR2(7),
    DRIVER_NAME VARCHAR2(12),
    DRIVER_CITY VARCHAR2(17),
    CONSTRAINT D_NO_PK PRIMARY KEY (DRIVER_NO)
);

INSERT INTO TEAM VALUES ('1','Ferrari',120000.00);
INSERT INTO TEAM VALUES ('2','Redbull',200000.50);
INSERT INTO TEAM VALUES ('3','McLaren',100000.00);
INSERT INTO TEAM VALUES ('4','Mercedes',93000.70);

INSERT INTO DRIVER VALUES ('C-101','Max','Amsterdam');
INSERT INTO DRIVER VALUES ('C-102','Piastri','Melbourne');
INSERT INTO DRIVER VALUES ('C-103','Norris','Bristol');
INSERT INTO DRIVER VALUES ('C-104','Leclerc','Monte Carlo');
INSERT INTO DRIVER VALUES ('C-105','Hamilton','Bristol');

ALTER TABLE DRIVER ADD DATE_OF_BIRTH DATE;
ALTER TABLE DRIVER RENAME COLUMN DRIVER_NO TO DRIVER_ID;
ALTER TABLE TEAM ADD CONSTRAINT TID_PK PRIMARY KEY (TEAM_ID);


SELECT * FROM TEAM  WHERE BUDGET>(SELECT BUDGET FROM TEAM WHERE NAME = 'Ferrari');
SELECT DRIVER_ID, DRIVER_NAME FROM DRIVER WHERE DRIVER_CITY != 'Bristol';
UPDATE DRIVER SET DRIVER_CITY = 'Sydney' WHERE DRIVER_ID = 'C-101';
UPDATE TEAM SET BUDGET = BUDGET * 0.75 WHERE BUDGET>(SELECT BUDGET FROM TEAM WHERE NAME = 'McLaren');
UPDATE TEAM SET BUDGET = BUDGET - 20000.00 WHERE TEAM_ID = '3';
UPDATE TEAM SET BUDGET = BUDGET - 20000.00 WHERE TEAM_ID = '2';

DELETE FROM TEAM WHERE BUDGET < (SELECT BUDGET FROM TEAM WHERE TEAM_ID = '4');

-- SELECT * FROM TEAM;
-- SELECT * FROM DRIVER;
DROP TABLE TEAM;
DROP TABLE DRIVER;