SELECT FIRST_NAME, COUNT(*)
FROM ARTIST
GROUP BY FIRST_NAME
HAVING COUNT(*)>1;

SELECT al.TITLE FROM INCLUDES inc, ALBUM al
where inc.ALB_ID = al.ALB_ID and inc.SONG_ID=NULL;

SELECT MAX(RELEASE_YEAR) - MIN(RELEASE_YEAR) FROM ALBUM;

SELECT NVL(COUNT(ra.SONG_ID),0), SONG.TITLE FROM RATING ra, SONG
WHERE ra.SONG_ID = SONG.SONG_ID
GROUP BY SONG.TITLE;




